### ISSUE TITLE
bug #24644: Units moving after in game help exit

### ISSUE THREAD

**Issue by michael-r-kolar** [TakingInitiative/wesnoth#29]
http://gna.org/bugs/?24644

**Comment by binarycoder** [comment]
/src/tooltips.cpp line 221 opens help dialog. Just need to figure out how to deselect a unit.

**Comment by michael-r-kolar** [comment]
We may be able to use the methods in wesnoth/src/mouse_events.cpp to deselect the current unit on help prompt.

**Comment by qmo2015** [comment]
The method select_or_action() on line 512 in wesnoth/src/mouse_events.cpp is accidentally called when exiting the help menu, causing the movement.

**Comment by qmo2015** [comment]
Whenever a player clicks during a game, function "left_click()" will be called and function "select_or_action()" will be function after that. "left_click()" checks if the player clicked on the minimap or the tooltips. "select_or_action()" selects a unit or makes the selected unit move to a destination. When a player clicks on the tooltips, "left_click()" is called and the help menu shows up. If there is a selected unit and the user tries to exit the help menu, the location of the cursor will be passed into "select_or_action()". "select_or_action()" then moves the selected unit to the location. 

The bug can be fixed by moving the process of checking if the player clicked on the tooltips from "left_click()" to "select_or_action()".
